# Generated by Django 5.2.8 on 2025-11-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre descriptif du document', max_length=200, verbose_name='Titre du document')),
                ('content', models.TextField(help_text='Texte complet du document (200-500 mots recommandés)', verbose_name='Contenu du document')),
                ('document_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('fitness', 'Fitness'), ('motivation', 'Motivation'), ('sante', 'Santé')], help_text='Catégorie du document', max_length=20, verbose_name='Type de document')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'Arabe'), ('es', 'Español'), ('de', 'Deutsch')], default='fr', help_text='Langue dans laquelle est rédigé le document', max_length=10, verbose_name='Langue du document')),
                ('keywords', models.JSONField(default=list, help_text='Liste des mots-clés pour la recherche', verbose_name='Mots-clés')),
                ('tags', models.JSONField(default=list, help_text='Tags supplémentaires pour la classification', verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour masquer le document sans le supprimer', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Document de connaissance',
                'verbose_name_plural': 'Documents de connaissance',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='fitness_bot_documen_ab23bc_idx'), models.Index(fields=['language', 'is_active'], name='fitness_bot_languag_876094_idx'), models.Index(fields=['is_active'], name='fitness_bot_is_acti_9710a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identifiant unique pour la session utilisateur', max_length=100, unique=True, verbose_name='ID de session')),
                ('user_level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', help_text="Niveau d'expérience en fitness de l'utilisateur", max_length=20, verbose_name='Niveau utilisateur')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'Arabe'), ('es', 'Español'), ('de', 'Deutsch')], default='fr', help_text="Langue préférée de l'utilisateur", max_length=10, verbose_name='Langue préférée')),
                ('goals', models.JSONField(default=list, help_text="Liste des objectifs de l'utilisateur", verbose_name='Objectifs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateur',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['session_id'], name='fitness_bot_session_e5a030_idx'), models.Index(fields=['last_activity'], name='fitness_bot_last_ac_b259e7_idx'), models.Index(fields=['language'], name='fitness_bot_languag_939439_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text="Message envoyé par l'utilisateur", verbose_name='Message utilisateur')),
                ('bot_response', models.TextField(help_text='Réponse générée par le chatbot', verbose_name='Réponse du chatbot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('session', models.ForeignKey(help_text='Session utilisateur associée', on_delete=django.db.models.deletion.CASCADE, to='fitness_bot.usersession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='fitness_bot_session_aa61b2_idx'), models.Index(fields=['timestamp'], name='fitness_bot_timesta_280c58_idx')],
            },
        ),
    ]
