# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

# config/routes.yaml
app_diet_form:
    path: /diet-form
    controller: App\Controller\DietController::dietForm
    methods: [GET, POST]

app_diet_results:
    path: /diet-results/{id}
    controller: App\Controller\DietController::dietResults
    methods: [GET]

app_my_diet_plans:
    path: /my-diet-plans
    controller: App\Controller\DietController::myDietPlans
    methods: [GET]
app_workout_personalized:
        path: /workout/personnalise
        controller: App\Controller\WorkoutController::index
        methods: [ GET, POST ]
app_workout_show:
        path: /workout/mon-programme/{id}
        controller: App\Controller\WorkoutController::show
        methods: [ GET ]
